### ISSUE TITLE
Undescribed error

### ISSUE THREAD

**Issue by matrumz** [DrDynamic/dotbot-sudo#5]
Running this plugin on a fresh WSL (Ubuntu) system with python 2.7 & 3.6 installed, and getting the following output
```
~/.system-bootstrap  master ✗                                                                                                                                                                                     1h6m ⚑ ✚ ◒  ⍉
▶ ./install-standalone fish
An error was encountered while executing action sudo
Action sudo not handled

==> Some tasks were not executed successfully
```
config file:
```
- sudo:
    - aptget:
        fish:
          ppa_source: ppa:fish-shell/release-3
          upgrade: true
```

I know this isn't a lot of info... is there anything I can do to get more info to troubleshoot/resolve this issue?
